---
version: 0.1.5
slug: hassio_boringproxy
name: BoringProxy-client for Home Assistant
url: https://github.com/jeynek/hassio_boringproxy
description: Simple client that connects to a BoringProxy-server. A way to give HomeAssistant a public IP without too much hassle.
codenotary: notary@home-assistant.io
advanced: true
arch:
  - amd64
host_network: true
options:
  server: myserver.io
  user: admin
  token: 12345678abcdefgh
  clientid: ha
  timeout: 10000h
schema:
  server: str
  user: str
  token: str
  clientid: str
  timeout: list(3h|4h|5h|6h|24h|72h|10000h)?
startup: application
init: false
